### ISSUE TITLE
cannot looking enlarged drawings

### ISSUE THREAD

**Issue by NovaGorica** [SpeciesFileGroup/taxonpages#101]
Dear administrator
Congratulations on this excellent database. I use it regularly and also cite it in my papers.  
But I have a problem: I can see enlarged photos in the display window above the figures, but not the enlarged drawings (see attachment). What could be the cause?
Thanks in advance for your reply
Best wishes.
Gabrijel Seljak

![same_drawing](https://github.com/SpeciesFileGroup/taxonpages/assets/138059126/7e85b4b0-ae8c-4372-b1d1-be5841c45571)
![aedeagus_photo](https://github.com/SpeciesFileGroup/taxonpages/assets/138059126/6a94490c-a458-47fa-8840-cfa32ca54f16)

**Comment by jlpereira** [comment]
Duplicate https://github.com/SpeciesFileGroup/taxonpages/issues/99, https://github.com/SpeciesFileGroup/taxonpages/issues/17
