### ISSUE TITLE
Add organization to attribution

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonpages#124]
Please add organization in attribution of the image. This is a requirements of the collections when they share their photographs.

**Comment by mjy** [comment]
Fixed in https://github.com/SpeciesFileGroup/taxonworks/issues/3515.

**Comment by proceps** [comment]
I do not see the fix. No license spelled, no organization.
https://hoppers.speciesfile.org/otus/54319/overview
![image](https://github.com/SpeciesFileGroup/taxonpages/assets/5597748/dfda4973-87b9-4f1e-94f5-0eec0a41be97)

**Comment by jlpereira** [comment]
<img width="404" alt="image" src="https://github.com/SpeciesFileGroup/taxonpages/assets/16530364/90cfe546-f8e9-4d8c-8360-09b6863286dd">

@proceps this is already fixed, but the change is not live on production yet. You can test it on local
