### ISSUE TITLE
Add auto-create retrieval date into footer citation

### ISSUE THREAD

**Issue by debpaul** [SpeciesFileGroup/taxonpages#137]
### Feature or enhancement

Request: make it so we do not have the string `[retrieval date]` in footer citations. Instead, auto-generate date=today when page/s load.

Add a function to auto-generate **today's date** to appear in the footer of each page.

(So I guess this would have to be some setting in a config file setting?)

### Location

the footer of all our taxon pages

### Screenshot, napkin sketch of interface, or conceptual description

![image](https://github.com/SpeciesFileGroup/taxonpages/assets/2990155/65a54755-9614-4389-a56e-b856a3cd56b3)

### Your role

Liaison

**Comment by lvhart2** [comment]
Adding to this issue: 

Please include the **true year** in the citation as well, after the authors and before "Plecoptera Species File".

**Comment by jlpereira** [comment]
Done

**Comment by lvhart2** [comment]
Retrieval date was added, Thank you! But can you add year to the citation after the authors? So that it looks like the citation from the old website: 

<img width="714" alt="Screenshot 2023-09-14 at 9 43 39 AM" src="https://github.com/SpeciesFileGroup/taxonpages/assets/75492546/a4c41ae3-f447-475e-8c0e-6b01f9081b69">

**Comment by mjy** [comment]
@lvhart2 @debpaul  Is the year the same thing in both cases?  For example, the first year is the year the cited thing was made available.  For specific versions this could be fixed (if people use versions).  This is different than the year the thing was accessed.  Or is it?

**Comment by proceps** [comment]
that is how I cite my site: Dmitriev, et al. (2022 onward).
