### ISSUE TITLE
Add attribution when GBIF map tiles are used

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonpages#145]

**Comment by timrobertson100** [comment]
Thanks indeed for alerting us to use of GBIF map use on [this example](https://jlpereira.github.io/taxonpages_osf/#/otus/17336/overview).
Could you please have that show "GBIF.org" instead of GBIF link through to http://gbif.org?

Thanks

**Comment by proceps** [comment]
Is it done?

**Comment by jlpereira** [comment]
It's done
