### ISSUE TITLE
stats panel

### ISSUE THREAD

**Issue by klausriede** [SpeciesFileGroup/taxonpages#154]
### Feature or enhancement

I still do not understand this statistics
![grafik](https://github.com/SpeciesFileGroup/taxonpages/assets/12816652/21756379-71e2-4fbd-bf57-f3595e8ea3e6)

where do I find an explanation? If a short explanation is available it might appear as hovering text
Refers to https://sfg-taxonpages.github.io/orthoptera/#/otus/813156/overview

### Location

Nomenclature panel TP

**Comment by proceps** [comment]
same as #71 The synonyms of self not calculated. Also a proposal to hide the left side of the stats, and add a button "Show more" to display this information. For unfamiliar people it is more confusing than informative.

**Comment by klausriede** [comment]
Another issue I write here because I did not find the correct place to submit this more general taxonworks question: I am not sure if you know the Berlin model here some Info https://www.bgbm.org/BioDivInf/Projects/MoreTax/default.htm

I wonder if taxonworks can model these distinct taxonomic views, and how they are implemented in the rel. database

**Comment by proceps** [comment]
The number of valid / invalid names is off the count again:
https://hoppers.speciesfile.org/otus/44300/overview
I am on the species page with two sysnonyms, it should be 1 | 2
![image](https://github.com/SpeciesFileGroup/taxonpages/assets/5597748/e3d922bd-fe78-4271-9f7e-7da25e536965)
The genus page with 11 synonyms, it should be 1 | 11
https://hoppers.speciesfile.org/otus/44941/overview
It always displays 2 valid names for self

**Comment by klausriede** [comment]
still not sure why we need this panel. It is confusing

**Comment by klausriede** [comment]
why is this issue closed`?

**Comment by mjy** [comment]
Duplicate of https://github.com/SpeciesFileGroup/taxonpages/issues/172.
