### ISSUE TITLE
group depictions according to providence

### ISSUE THREAD

**Issue by klausriede** [SpeciesFileGroup/taxonpages#157]
### Feature or enhancement

http://orthoptera.speciesfile.org/Common/specimen/ShowSpecimen.aspx?SpecimenID=42737
Syntype pictures appear in https://sfg-taxonpages.github.io/orthoptera/#/otus/822435/overview but you have to hover over each of them to see the syntype status. Better group them together. In addition, I wonder if syntypes should be listed within the section type specimen(s) particularly if they are depicted

### Location

Nomenclature panel TP

**Comment by MMCigliano** [comment]
The new Specimen Records tab lists each specimen separately.

**Comment by klausriede** [comment]
Yes that was a major improvement!
