### ISSUE TITLE
2FA authent and my feedback

### ISSUE THREAD

**Issue by klausriede** [SpeciesFileGroup/taxonpages#158]
### Feature or enhancement

github is now requiring 2FA which is far too complicated for me (and seems quite invasive), particularly because my github projects are closed. However, I would love to continue to contribute to taxonpages. I suppose there are many more users who might contribute but are not even on github. So the question is if there are alternatives to submit remarks and suggestions. I am not sure if I will be excluded immediately on 28th, so please comment via the other taxonworks channels, if necessary

### Location

General remark

**Comment by mjy** [comment]
2FA does take a little to setup, but it's no different than logging on to an account once in a while.  You only have to authenticate with a second "factor" once in a while, your account will be remembered just like your other logins.  I use the Duo app, it auto-pings me when I try to do something that requires it, I click one thing and I'm good for weeks, in your cases essentially until you log out of GH.   I only need to re-use when I'm doing admin changes, something you will never have to do on these repos.  

2FA helps to ensure we are not invaded by someone who is pretending to be you, and protects you in many ways.  Of all the different things to worry about on the internet this is not one of them in my opinion.

At this point we are not planning other issue tracking mechanisms.

**Comment by klausriede** [comment]
Thanks so I will try this. In fact having an account unauthentificated hanging around here might become a problem

**Comment by mjy** [comment]
@klausriede Google' `Authenticator` is another common app, I do have both setup.

**Comment by klausriede** [comment]
thanks I think I will take this because I have them already on my cellphone!
