### ISSUE TITLE
Reduce maximum default zoom of map?

### ISSUE THREAD

**Issue by typophyllum** [SpeciesFileGroup/taxonpages#165]
In a species with a single georeferenced type one has to zoom out up to ten times to see where on the map it is actually located.

**Comment by typophyllum** [comment]
default
![imagen](https://github.com/SpeciesFileGroup/taxonpages/assets/33210201/c3a9fb66-d6aa-4dab-a2c7-3606d50e62aa)

zoom out once
![imagen](https://github.com/SpeciesFileGroup/taxonpages/assets/33210201/8d82e988-59d5-4ffe-b569-733b5e5fdf76)

zoom out a second time
![imagen](https://github.com/SpeciesFileGroup/taxonpages/assets/33210201/8e8d104c-8b30-4208-aebc-fb487c308500)

third time
![imagen](https://github.com/SpeciesFileGroup/taxonpages/assets/33210201/2d51ba8c-4c51-47fd-b0f1-d68d8f23e13d)

forth time
![imagen](https://github.com/SpeciesFileGroup/taxonpages/assets/33210201/c5c0c740-c150-4bae-8c38-60c812bd685b)

fifth time
![imagen](https://github.com/SpeciesFileGroup/taxonpages/assets/33210201/45bc3d64-3aea-4cc8-a1e4-f06304fb2903)

sixth time
![imagen](https://github.com/SpeciesFileGroup/taxonpages/assets/33210201/a2558238-7b1b-4baf-85ed-b78e291e8730)

seventh time
![imagen](https://github.com/SpeciesFileGroup/taxonpages/assets/33210201/f7e41e7a-3d22-45d0-8662-66ae21de5dd2)

eigth time
![imagen](https://github.com/SpeciesFileGroup/taxonpages/assets/33210201/f32eda3a-f425-4da4-b147-bcb67fd27ba6)

ninth time
![imagen](https://github.com/SpeciesFileGroup/taxonpages/assets/33210201/f35cd01e-aa5d-489f-85d4-751bc3469a74)

tenth time, finally it is clear that it's in Costa Rica
![imagen](https://github.com/SpeciesFileGroup/taxonpages/assets/33210201/d9427312-5ae9-4ed0-a52f-6e636ada97a4)

**Comment by jlpereira** [comment]
@typophyllum could you share the link to this page?
