### ISSUE TITLE
Map geographic/political names not in English

### ISSUE THREAD

**Issue by redewalt** [SpeciesFileGroup/taxonpages#166]
### Feature or enhancement

I don't want to be too USA centric, but is there a way to get the maps on the public UI to provide English country names, maybe depending upon who uses it or maybe through some choice I make when viewing the map.

### Location

Map

### Screenshot, napkin sketch of interface, or conceptual description

![Map names DeWalt](https://github.com/SpeciesFileGroup/taxonpages/assets/30870810/eb47067d-3c95-4b4d-b76c-ae1856f48a53)

### Your role

Ed DeWalt

**Comment by mjy** [comment]
@redewalt we can switch the base tiles per TP instance to the GBIF tileset, which is English.  The tradoff is that the tileset can load slower, and there is much less annotation than on OpenStreetMap.  We did this for you on Plecoptera.
