### ISSUE TITLE
References: Words in reference are split. 

### ISSUE THREAD

**Issue by redewalt** [SpeciesFileGroup/taxonpages#169]
### Feature or enhancement

The reference string wraps in the space provided. Frequently, words are split in the middle. It doesn't look professional. Is there a setting that keeps a word together so that it is shown entirely one line or the next?

### Location

References panel

### Screenshot, napkin sketch of interface, or conceptual description

I don't think it necessary here.

### Your role

The boss.

**Comment by mjy** [comment]
Can you prevent wordbreak here @jlpereira?

<img width="799" alt="Screenshot 2023-10-06 at 9 36 53 AM" src="https://github.com/SpeciesFileGroup/taxonpages/assets/22600/91d4b7dc-f878-4175-bacd-e6efec1e657c">

**Comment by jlpereira** [comment]
Yes, I will fix this, but we still need to break the links. Because some links are too long and overflow the panel.

**Comment by jlpereira** [comment]
It's fixed.
