### ISSUE TITLE
As a user I want to understand what questions are being answered by the Stats pannel [was: Species rank [Panel]: }

### ISSUE THREAD

**Issue by klausriede** [SpeciesFileGroup/taxonpages#172]
### Your role

biologist

### Your needs

still do  not understand the function of this panel
![grafik](https://github.com/SpeciesFileGroup/taxonpages/assets/12816652/7a22074f-7c8d-4bf1-9720-e3fea9679cda)

here from https://sfg-taxonpages.github.io/orthoptera/#/otus/811846/overview

but in any case what does this panel mean? Where do I find an explanation of what I see on taxonpages?

### Audience question

not sure if my question is placed here correctly

### Audience

NOT kindergarten

### Header

undefined elements in taxonpages

### Data

N/A

**Comment by proceps** [comment]
it should be fixed now. There was an error in stat calculation.
