### ISSUE TITLE
images displaying

### ISSUE THREAD

**Issue by cicadina1** [SpeciesFileGroup/taxonpages#179]
### Steps to reproduce the bug

```bash
some images are not displayed in the site
```

### Screenshot

![error_SF](https://github.com/SpeciesFileGroup/taxonpages/assets/58778743/6bee20d7-1423-4d24-a033-b15f03660f65)

### TaxonPages Site URL

https://hoppers.speciesfile.org/otus/27444/overview

### TaxonPages Panel

images

### Browser Used

Firefox

**Comment by jlpereira** [comment]
Duplicate: https://github.com/SpeciesFileGroup/taxonpages/issues/17

Hello @cicadina1

This is a known issue, web browsers don't support TIFF images. We will fix this from TaxonWorks side converting the images into a supported format.

**Comment by cicadina1** [comment]
those image was png

**Comment by jlpereira** [comment]
<img width="379" alt="image" src="https://github.com/SpeciesFileGroup/taxonpages/assets/16530364/9696b6dc-cb52-401c-a309-99d9a6c7f0a7">

@cicadina1 no all the images there are in png format, thumbnails are in png for example. But the drawing images are not, they are in TIF format as you can see on the image

**Comment by cicadina1** [comment]
or maybe just the preview thumbnails were png
