### ISSUE TITLE
A table showing the limitations of our data

### ISSUE THREAD

**Issue by DavideDalPos** [SpeciesFileGroup/taxonpages#196]
### Feature or enhancement

Dear All,

Recently, I did a little bit of effort to improve the TaxonPages layout. I was able to download and "copy" the codes done by Jose' for the Orthoptera Species File in VUE, and modified them to match what I needed. You can see it [here](https://davidedalpos.github.io/WID_Ichneumonidae/#/).

On top of this, I was looking to do one other cool thing that will be important for the user: since the group is big, we would like to publicize the page in a data-paper soon (before all the subfamilies are completed). However, we would like the user to know what subfamilies are missing data and which are completed. I thought, therefore, that a table that gives information on exactly at what stage in the process we are for each subfamilies, would be great. For instance, we know that all the species of the subfamily Ichneumoninae from Africa are included with their taxonomic history, but not their distribution. We would like to capture that, and make sure that whoever uses the data, knows the limitations. Therefore, I went ahead and created a table in VUE following a tutorial online. You can see the table I created in the link [here ](https://davidedalpos.github.io/WID_Ichneumonidae/#/subfamilies) (please, ignore the value inside: they are simply placeholders for the moment). As you can see, the last row has "Links" which are connected for each subfamily, to their OTU page in TaxonPages. For me it is really cool (proud of it, even though it is very simple!) :-)  

I wanted also to add a search bar, that helps the reader filter the subfamilies, and then maybe add a button filter to filter some values other than the subfamily name. However, despite being able to add the search bar, every time I input the computed function to filter in the search bar (no matter what's inside) the entire page becomes blank (after the committing is successful). I tried everything (and spent too much time on it), and I am not able to resolve it or understand what I did wrong. Since I was following that tutorial, and since I am not a programmer, I am not sure how to find a way around it.

Maybe some of you can give me a lead? 

This is the github poge of the project where the codes are updated: https://github.com/DavideDalPos/WID_Ichneumonidae 
Maybe I need to mention that I am using VS code on Windows via gitter.

Thank you again for any help,
Davide

### Location

https://github.com/DavideDalPos/WID_Ichneumonidae

**Comment by jlpereira** [comment]
Sorry @DavideDalPos , I saw your message on Zoom after you leave. 
Just to give you an update on this, for your requirement it seems not possible right now and it will need a new endpoint to get the data. You will have to ping Matt for it, unless you have the data hard coded and you want to show it on a table. I can help you building this table and filters for it, but you will need the data first

**Comment by DavideDalPos** [comment]
@jlpereira Thank you for the message! :-) 

I was not looking for a table that imports data from TW, but simply to display a table which is built by me (by manual entry) to show temporarily data in taxonpage. All this in order to inform people about what we are doing and what data are missing. As you saw, I have the framework done, but I am missing something when try to build the filter. I think it has something to do with the "onMounted" function, but I am too stupid to figure it out :-) 

If you could help me out (briefly) that would be awesome and I would like to re-pay you in anyway possible :-) We can do a zoomcall so I can show what I have done so far or I can do screenshots :-) 

Thank you so much,
Davide

**Comment by jlpereira** [comment]
Can you point me where is your data, @DavideDalPos ?

**Comment by DavideDalPos** [comment]
@jlpereira sure! 

You can find everythin in my setup branch: https://github.com/DavideDalPos/WID_Ichneumonidae

Everything is in components, and I have 3 _.vue_ entries: 

- DataTable.vue (https://github.com/DavideDalPos/WID_Ichneumonidae/blob/setup/pages/components/Section/Data/DataTable.vue ; pages>components>Section>Data) which contains the framework for the table with the search bar
- App.vue (https://github.com/DavideDalPos/WID_Ichneumonidae/blob/setup/pages/components/Section/App.vue ; pages>components>Section) which contains the actual table with data
- subfamilies.vue (https://github.com/DavideDalPos/WID_Ichneumonidae/blob/setup/pages/subfamilies.vue ) which is the page where the table is shown. 

On top of these I have the SearchForm.vue which contains the _emits_ and the template for the search bar: https://github.com/DavideDalPos/WID_Ichneumonidae/blob/setup/pages/components/Section/Data/SearchForm.vue

I do not have the computed function included at the moment because when I do, the entire table disappear in TaxonPages (you can see here the table: https://davidedalpos.github.io/WID_Ichneumonidae/#/subfamilies

I think the problem is in the App.vue (I did not put the "onMounted" function maybe?)

What do you think? 

Davide

**Comment by jlpereira** [comment]
@DavideDalPos download this zip, and put the content inside `pages/components` folder.

Zip: [subfamilies.zip](https://github.com/SpeciesFileGroup/taxonpages/files/13733584/subfamilies.zip)

Update your `pages/subfamilies.vue` file with this:

```vue
<template>
  <VCard class="m-8">
    <DataTable :items="subfamilyData" />
  </VCard>
</template>

<script setup>
import DataTable from './components/subfamilies/DataTable.vue'
import subfamilyData from './components/subfamilies/subfamiliesData.js'
</script>
```

I moved your data into a js file. You can remove the components you added on `Section/Data` and `App.vue`
If you want to add more stuff to the table, make a list and I will be happy to help you.

**Comment by jlpereira** [comment]
Btw, I made some changes on your style to make it work on both themes, light and dark

**Comment by DavideDalPos** [comment]
@jlpereira OH MY GOSH!! You are the best! A GOD, I would say! It works perfectly! My gosh!! 

First of all: thank you so much for taking the time and doing this!
Second: I will put your name as the contributor/facilitator for the codes! You are the best! THe next species I describe, it will have your name! 
Third: I completely forgot to add you as collabprator to the Repository before. I apologize! I just sent you the invitation. :-) 

I should be able to add more "rows" to the table, but if I need some other filter, I will make sure to contact you directly. 

Again, I am not sure how to repay you for this. I was banging my head for weeks for this! 

Now I will try to understand what you have done, so I know for the future. Thank you so much again! 

A big hug,
Davide

**Comment by jlpereira** [comment]
xD

Your welcome, and sorry for the delay on this, I thought you would need an endpoint for it. Do not hesitate to contact us when you need something for your site, we have already made adaptations for other users too.

I'm closing this, remember you can contact me/us directly on Gitter if you need help with your TaxonPages site
