### ISSUE TITLE
no maps at genus and higher

### ISSUE THREAD

**Issue by typophyllum** [SpeciesFileGroup/taxonpages#203]
Only the species pages display maps, at all higher ranks the maps are empty.

**Comment by mjy** [comment]
@typophyllum If you can please join our slack/chat channels (links at https://speciesfilegroup.org/events.html).  We discuss re-indexing data (as we are doing now for maps) there so these kind of things may become less of a suprise..

 I realize we need to better communicate this in TaxonPages as well, maybe we can return a response indicating "Re-indexing".
 
 FYI, the current re-indexing will be done in about 6-8 hrs, however there remain issues that we think we have a clue on (our gis component of the underlying database, not TaxonWorks code, needs updating).
