### ISSUE TITLE
type specimen of new nominotypical subspecies not displayed under Specimen records

### ISSUE THREAD

**Issue by typophyllum** [SpeciesFileGroup/taxonpages#208]
I added a new subspecies to _Mirollia_ (_Mirollia_) _fallax_ and the soft validation fix created the nominotypical subspecies _Mirollia_ (_Mirollia_) _fallax fallax_. Its holotype is missing on the Specimen records tab (regenerate DwC of the collection object doesn't help):
![imagen](https://github.com/SpeciesFileGroup/taxonpages/assets/33210201/df6e3069-9861-480f-b466-e048f961c3f1)

It is only displayed at the species:
![imagen](https://github.com/SpeciesFileGroup/taxonpages/assets/33210201/9b41aa59-4e97-4991-b176-08734cddb96e)

The OTU of _Mirollia_ (_Mirollia_) _fallax fallax_ in TaxonWorks does show the holotype.

**Comment by proceps** [comment]
sv does add type material. Follow sv messages. It probably took time to generate DWC. I went to orthoptera.speciesfile.org, and it shows the record now.
![image](https://github.com/SpeciesFileGroup/taxonpages/assets/5597748/e3b9730c-8d88-4b41-8b16-0f126edeca97)

**Comment by proceps** [comment]
The type status present
![image](https://github.com/SpeciesFileGroup/taxonpages/assets/5597748/ae1c1d1e-59b8-47fe-9d64-346211b90f0e)
The specimen is recorded as a type for both species and subspecies.
Indexing does not show the specimen as a type:
![image](https://github.com/SpeciesFileGroup/taxonpages/assets/5597748/a09f9e9d-af68-43c7-9a26-7415f473a9ba)

**Comment by mjy** [comment]
Has it been re-indexed?

**Comment by typophyllum** [comment]
The holotype (from China, Nandinhe River) is still missing on the specimen tab of _M_. (_M_.) _f. fallax_. The specimen from Vietnam is not a type.

**Comment by proceps** [comment]
I think, the problem is that the specimen are showed by their determination OTU, and not by type status. A specimen could be the type for 2 and more species names, but I could have only single current determination.

**Comment by proceps** [comment]
I would recommend to put the determination as subspecies, in this case, you will see a dot on the map for both, species and subsspecies.
