### ISSUE TITLE
wrong image in Type specimen panel (correct in Overview and TW)

### ISSUE THREAD

**Issue by typophyllum** [SpeciesFileGroup/taxonpages#209]
Correct in Browse OTU at _Metrodora arcuata_ (Bruner, 1920)
![imagen](https://github.com/SpeciesFileGroup/taxonpages/assets/33210201/01f6e12e-8283-48f0-a458-c9dceca5153a)

Type specimen panel with image swap:
![imagen](https://github.com/SpeciesFileGroup/taxonpages/assets/33210201/a591f538-72ff-478b-b420-e9dcdb85a8b1)
![imagen](https://github.com/SpeciesFileGroup/taxonpages/assets/33210201/afc0b944-a8f2-479b-ba16-23f38e589b65)

The same image of the line drawing is displayed correctly in the Overview of  _Coyacris collis_ Ronderos, 1991.

**Comment by typophyllum** [comment]
Another case of a wrong photo, this happened very recently upon adding new pictures.
_Chibchacris furcata_, penultimate specimen:
https://orthoptera.speciesfile.org/otus/816354/specimen_records

TW (09e3c5fe-9b46-4da8-9ba9-6c859f5ec16c det. _Chibchacris furcata_ Hebard, 1923):
![imagen](https://github.com/user-attachments/assets/cfb515b3-1923-4033-a62a-1d27b3d2fb19)

TP:
![imagen](https://github.com/user-attachments/assets/eaaf9a98-61ac-4f9f-94a9-c9bec9ac4c7f)

The wrong photo is of _Pycnopalpa bicordata_ , 39th picture in Overview:
https://orthoptera.speciesfile.org/otus/849521/overview

Lost photo:
https://sfg.taxonworks.org/images/1096284
Short URL to original: https://sfg.taxonworks.org/s/2kd8gl

Infiltrated photo:
https://sfg.taxonworks.org/images/975145
 Short URL to original: https://sfg.taxonworks.org/s/xldc85

**Comment by typophyllum** [comment]
In the Overview of _Ch. furcata_ apears the correct photo (24th image):

![imagen](https://github.com/user-attachments/assets/23b3bbb2-64cf-4a01-9da8-26943d64a41d)

**Comment by typophyllum** [comment]
@jlpereira Any idea what's happening here?

**Comment by jlpereira** [comment]
Yes, there is a bug loading images from dwc endpoint related to the image's fingerprint. 
This only happens on Specimen Records tab, right?

**Comment by typophyllum** [comment]
Yes, only with the Specimen Records.

**Comment by typophyllum** [comment]
Another one:

![imagen](https://github.com/user-attachments/assets/cb7af5e0-48d7-460e-8243-b70e52969b4f)

![imagen](https://github.com/user-attachments/assets/92744f82-5bd0-4af8-b33c-edfa389e944d)
