### ISSUE TITLE
[Bug]: Specimens records and iNaturalist panel not listing specimens

### ISSUE THREAD

**Issue by DavideDalPos** [SpeciesFileGroup/taxonpages#221]
### Steps to reproduce the bug

```bash
1. If you go into WID (https://worldichneumonidae.com/) and look for a species (e.g., Diadromus collaris), there is no listing of specimens under "Specimens records" and no images under "iNaturalist" panels
```

### Screenshot

![Screenshot 2024-08-20 170626](https://github.com/user-attachments/assets/e57eee1c-ee20-41ca-959d-0cd8c408c1f1)

### TaxonPages Site URL

https://worldichneumonidae.com

### TaxonPages Panel

https://worldichneumonidae.com/#/otus/783944/specimen_records

### Browser Used

Chrome

**Comment by jlpereira** [comment]
Fixed
