### ISSUE TITLE
[Bug]: When a genus has more than one superspecies within it, only one is rendering on TaxonPages

### ISSUE THREAD

**Issue by hhopkins77** [SpeciesFileGroup/taxonpages#228]
### Steps to reproduce the bug

```bash
1.When in TaxonPages I go to a genus with more than one superspecies, and with species outside of superspecies groupings, only the first superspecies is rendering.
2.See https://cockroach.speciesfile.org/otus/862507/overview
3.You can see in the Stats box (below) that there are supposed to be 2 superspecies, and that there are a total of 31 valid and invalid species, but only one superspecies and 4 species are rendered
...
```

### Screenshot

![image](https://github.com/user-attachments/assets/9e945dc7-faf3-40b6-ace0-8f45dbf52f93)

### Expected behavior

When I look at a TaxonPage I expect to see all the taxa entered for any given taxonomic level.

### TaxonPages Site URL

https://cockroach.speciesfile.org/otus/862143/overview

### TaxonPages Panel

Descendents and synonyms

### Browser Used

Chrome

**Comment by typophyllum** [comment]
In OSF it looks alright:

![imagen](https://github.com/user-attachments/assets/c400062a-65ce-48d8-9fec-e02e2b51a818)

**Comment by hhopkins77** [comment]
I've checked the other SF and this is only happening in the once instance listed here, that I can find (!)

**Comment by typophyllum** [comment]
Do the missing superspecies perhaps lacking OTUs?

**Comment by hhopkins77** [comment]
Yes! Great catch. All fixed.
