### ISSUE TITLE
GBIF copyright on maps

### ISSUE THREAD

**Issue by typophyllum** [SpeciesFileGroup/taxonpages#242]
This shows the type locality of a newly added species which isn't on GBIF yet, apart from that OSF distribution data are entirely independent from GBIF.

![imagen](https://github.com/user-attachments/assets/605eb017-8231-4df7-bc8e-6cebd99a6fb2)

**Comment by mjy** [comment]
GBIF is the map tile set being used, not the data.  We're are crediting them for that service.
