### ISSUE TITLE
Config TP to only show TW OTUs with CollectionObjects [Was: [Bug]: API Token accessing data outside of the database that the token is associated with.]

### ISSUE THREAD

**Issue by Shanetiltongc** [SpeciesFileGroup/taxonpages#252]
### Steps to reproduce the bug

```bash
1.Set up website template
2.Set the Database API token to link to UNH taxon works
3.Search for an insect, then the autofill will show species outside of what exist in the UNH taxon works database.
...
```

### Screenshot

![image](https://github.com/user-attachments/assets/10422dcc-3946-423c-ab77-e7c32746c3a6)

### Expected behavior

I expect the autofill feature to only show collection objects within the UNH taxon works database.

### TaxonPages Site URL

https://shanetiltongc.github.io/taxonpages/#/

### Browser Used

EDGE

**Comment by mjy** [comment]
@Shanetiltongc Welcome, thanks for posting.  I suspect something off with the config.

@jlpereira Can you poke at the setup, I suspect maybe the token is not being sent correctly?

**Comment by Shanetiltongc** [comment]
> I cannot reproduce, but I see a commit one hour ago changing the API token. Maybe you tested the site before the deployment of the changes completed?

The deployment of the changes seems to have gone through. My boss told me he thought that it was auto filling the data from the entire taxonomic database, rather than our specific taxonworks database. For example: it will auto fill this option; 'Andrena anzu Tadauchi and Hirashima, 1987' even though it does not appear that the UNH database has this insect in its collection.

**Comment by mjy** [comment]
I think I understand.   You want to limit the OTU pages to those that have collection objects, not display all the OTU pages that you have OTUs for in the database.

For example, you do have an OTU in that project with that name: https://sfg.taxonworks.org/otus/704976, it just doesn't have specimens.

Can you confirm this interpretation is correct?



Right now this isn't actually possible, it would require

**Comment by mjy** [comment]
So given this the feature is not yet possible, and it may be some time before it gets addressed.

**Comment by Shanetiltongc** [comment]
Good to know, thanks so much for the help!
