### ISSUE TITLE
As a Bioschemas contributor I want to markup a page with their Taxon model

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonpages#27]
https://bioschemas.org/profiles/Taxon/0.8-DRAFT

Example: https://github.com/BioSchemas/specifications/blob/master/Taxon/examples/0.7-DRAFT/Delphinapterus%20leucas_jsonld_0.7_full.json

HowTo: https://bioschemas.org/tutorials/howto/howto_add_markup

HowToExample: https://bioschemas.org/tutorials/what_why_schema#3-schemaorg-formats

**Comment by jlpereira** [comment]
Endpoint: `taxon_names/<id>/summary.json`

- [ ]  Add `parent` with `full_name` and `author`
- [ ]  Add taxonomic name without author
- [ ]  Add Identifiers for current name and parent

Endpoint: `/otus/<id>/inventory/taxonomy.json?extend[]=common_names`

- [ ] Add short language code to common names
