### ISSUE TITLE
Descendants and synonyms - Sorting

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonpages#35]
Please bring the descendants of a higher rank close to the top of the list. and sort the names alphabetically within the same rank category. An example from 3i: Fulgoromorpha has superfamilies, families and genera as children. 3 subfamilies should be listed at the top, unplaced families and genera should follow. Compare two images from TaxonPages and TaxonWorks:
![image](https://user-images.githubusercontent.com/5597748/228086237-5adbcccc-41b8-4698-a520-08b88185120d.png)
![image](https://user-images.githubusercontent.com/5597748/228086263-efd02090-004e-4d53-a829-16a93b03f312.png)

**Comment by mjy** [comment]
This result is a catalog timeline.  It is ordered by year of citation.

**Comment by proceps** [comment]
Synonyms should be ordered by the date, but the logic should be different for the descendants.

**Comment by proceps** [comment]
Yes, it make total sense to order synonyms by time. But for descendants, most of the catalogs list those alphabetically, and by rank, listing name with complete classification first, and put unplaced taxa closer to the bottom of the list.

**Comment by mjy** [comment]
What we might be saying is that it shouldn't be Descendants AND synonyms, it should be one or the other.

**Comment by proceps** [comment]
Yes, may be. We should discuss this with SF providers. Or make fully functional tree with collapsing and expanding nodes (loaded on demand).

**Comment by typophyllum** [comment]
Example: Genus _Phlugiolopsis_ has 5 subgenera (with altogether 33 species) and 19 species not assigned to subgenus. The current display with interspersed subgenera is really confusing.

![imagen](https://github.com/SpeciesFileGroup/taxonpages/assets/33210201/c946aa59-2305-49e0-ae23-224f5986c6c7)

**Comment by proceps** [comment]
a spec test added to otus_helper_spec.rb

**Comment by mjy** [comment]
See also miss-classification of species that are superspecies, being placed alphabetically.

https://plecoptera.speciesfile.org/otus/891621/overview

**Comment by MMCigliano** [comment]
@mjy what the status on this issue? thanks

**Comment by hhopkins77** [comment]
> See also miss-classification of species that are superspecies, being placed alphabetically.
> 
> https://plecoptera.speciesfile.org/otus/891621/overview

This is the issue that I brought to a Wednesday meeting a little while ago. Brought to meeting again by MM on 7/3.
