### ISSUE TITLE
Kickstart with working of taxon overview page

### ISSUE THREAD

**Issue by LocoDelAssembly** [SpeciesFileGroup/taxonpages#5]
To attempt determine how long will it take to make all of the public pages I propose we start by implementing the overview page, identify missing components in the API and implement them as well. Once done, also attempt making a build system and try out different approaches.

Bonus: also consider versioning? Must learn specifics of how EOL did this. Would git versioning work also?

Target approach for now: Either use Nuxt or Astro with Vue.

TODO: Consider PWA, do Nuxt/Astro provide good support for it?

**Comment by mjy** [comment]
Closing as outdated.
