### ISSUE TITLE
Panel - Nomenclature references: Taxon citation accompanied with TaxonName

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonpages#6]
Please add a taxon name before each nomenclatural citation.

**Comment by mjy** [comment]
This will not work because the reference section can have more than one name per source.

I believe we need a new panel (remember, all panels optional) to include what is the browse nomenclature section in TW.

**Comment by MMCigliano** [comment]
Is there any possibility to add a ne tab with the timeline that Jose has already designed in figma?

**Comment by dimus** [comment]
@gdower and @dimus talked about it a bit. Should we add an issue to create `TWindex` rake task that traverses all PDF files connected to citations and extracts names from them? So there is an info about all names connected to citations, we can also have name extraction from the title, if it is available (or just names from the first 200 words of PDF) to get most important names in the paper.

**Comment by proceps** [comment]
If there are multiple names per source, we should extend it to multiple lines in the entry.

**Comment by mjy** [comment]
@dimus What if we do the first non-taxonworks panel, Gnfinder?  It takes some params, and displays some result.  If we needed to we could feed it documents via a private API endpoint (or use an index). Maybe use a nix index, who knows. Part of the point is it would force us to try to build in a new resource, for a new panel. 

Even something like:

`Gnfinder verification`
...result...

**Comment by MMCigliano** [comment]
> Please add a taxon name before each nomenclatural citation.

Any progress?

**Comment by mjy** [comment]
Closing as complete.
