### ISSUE TITLE
Taxon/Nomenclature stats

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonpages#71]
* Probably rank dependenant
* Difference between names / OTUs in counts
* Mimic the existing stats endpoint?!

**Comment by proceps** [comment]
When I am on a species page with synonyms, the stats shows 1 valid name and 0 invalid. OTUs also showed as 1, although there should be 3.
An example: https://hoppers.speciesfile.org/otus/44286/overview

**Comment by proceps** [comment]
The same is also the case of the higher taxa. The synonyms of self are not counted. This is the page of subgenus:
https://hoppers.speciesfile.org/otus/46310/overview

**Comment by mjy** [comment]
Stats have been updated with an attempt to fix this.

**Comment by mjy** [comment]
Or not.  I changed but lost, re-adding.
