### ISSUE TITLE
cicada songs

### ISSUE THREAD

**Issue by klausriede** [SpeciesFileGroup/taxonpages#96]
Auchenorrhyncha files would be a great place to include information about songs, crucial for integrated taxonomy in acoustically communicating insect groups http://dmitriev.speciesfile.org/  - any plans?

**Comment by proceps** [comment]
Dear Klaus, Auchenorrhyncha data was migrated from 3i to TaxonWorks software 4 years ago. dmitriev.speciesfile.org has access to the original data, which were not updated for many years. All new information should be available at hoppers.speciesfile.org, the new data portal generated from TaxonWorks database. Please use it for up to date classification. I am really interested to accumulate all information related to Auchenorrhyncha in a single project, but I do not work with acoustics myself. Auchenorrhyncha project is a collaborative project with multiple curators. If somebody join the project and start curating acoustic data, I will be very happy to support (some of my collaborators already expressed interest). At the moment TaxonWorks do not have interfaces to work with media files, but we are definitely planning to do this in the future: https://github.com/SpeciesFileGroup/taxonworks/issues/244

**Comment by klausriede** [comment]
thanks, and yes, I would be interested to participate in curation, I could contribute cicada songs AND Orthoptera songs. Notabene: data management of song data is not restricted to multimedia management of wav files, on the contrary the interesting part begins with attributes of distinct sound parameters, verbal descriptions, keys - I do not see much difference to morphological data! For an example of (automatic) annotation see my paper http://www.groms.de/data/zoology/riede/RiedeetalJOR06.pdf
